version: "3.8"

services:

  web:
    build: .
    ports:
      - 8008:8000

  postgres:
    image: postgres:15-alpine
    volumes:
     - .volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 5432:5432
    env_file:
      - .env
