version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${APP_PORT}"  # Use APP_PORT from .env file
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - network_storage
    links:
      - database

  database:
    image: postgres:15-alpine
    volumes:
     - .volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - network_storage

networks:
  network_storage:
    driver: bridge
