"""refbook

Revision ID: 4f7dedec183c
Revises: ce80db2149b6
Create Date: 2024-03-14 11:25:45.338858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7dedec183c'
down_revision: Union[str, None] = 'ce80db2149b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.add_column('device', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'service_id')
    op.drop_table('service')
    # ### end Alembic commands ###
