"""empty message

Revision ID: 57bc6d05b2be
Revises: 8ab5a9d49632
Create Date: 2024-02-27 12:02:51.142094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bc6d05b2be'
down_revision: Union[str, None] = '8ab5a9d49632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('comment', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network', 'comment')
    # ### end Alembic commands ###
