"""empty message

Revision ID: 62a76fdb6ed5
Revises: 9913c32b6ed3
Create Date: 2024-02-26 15:32:21.069216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a76fdb6ed5'
down_revision: Union[str, None] = '9913c32b6ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('network_parent_id_fkey', 'network', type_='foreignkey')
    op.create_foreign_key(None, 'network', 'network', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.create_foreign_key('network_parent_id_fkey', 'network', 'network', ['parent_id'], ['id'])
    # ### end Alembic commands ###
