"""empty message

Revision ID: 8281990d4d62
Revises: 57bc6d05b2be
Create Date: 2024-02-27 13:34:29.278460

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8281990d4d62'
down_revision: Union[str, None] = '57bc6d05b2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('network_parent_id_fkey', 'network', type_='foreignkey')
    op.create_foreign_key(None, 'network', 'network', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.create_foreign_key('network_parent_id_fkey', 'network', 'network', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
