"""change network table

Revision ID: aef6ee025560
Revises: f7a6abc2c8ae
Create Date: 2024-02-22 13:32:34.062044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef6ee025560'
down_revision: Union[str, None] = 'f7a6abc2c8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('network', 'sub_network_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('sub_network_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('network', 'parent_id')
    # ### end Alembic commands ###
